parameters:
  input_size: 3
  action_size: 1
  k_step: 3
  hidden_size: 16
  num_layers: 1
  bias: True
  num_epochs: 1000
  lr: 0.0001
  save: True
  prefix: '_nonlinear_curr_1to3'
  curr_learning: True
  pre_trained_path: './checkpoints/lstm_auto_encoder/checkpoint_16h_1step_lstm_nonlinear.pth'
